### ISSUE TITLE
Access violation is thrown when clients sends an empty packet

### ISSUE THREAD

**Issue by la-legende** [imxeno/devtale#4]
Client throws memory error when trying to send message that contains only "`" sign.

**Comment by imxeno** [comment]
It's probably an access violation that occurs while attempting to create a string from a `char*` which is a `nullptr`. I'll look into it in the evening.

**Comment by imxeno** [comment]
![image](https://user-images.githubusercontent.com/10596740/98653671-971a6a00-233d-11eb-996a-d7e42ed18b35.png)

**Comment by imxeno** [comment]
Fixed in 483883f8db2fd5f0e6acbbb4d0c6582347db7c11.
